project:
  type: website

website:
  title: "Live Music Transcriber"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: fpga.qmd
        text: FPGA
      - href: mcu.qmd
        text: MCU
      - href: documentation.qmd
        text: Documentation
      - href: results.qmd
        text: Results
      - href: about.qmd
        text: Team

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
